version: "3"
services:
  config:
    image: "dhananjay12/config-server:latest"
    ports:
      - "8888:8888"
  eureka:
    image: "dhananjay12/eureka-server:latest"
    environment:
      - "SPRING_EUREKA=http://eureka:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=http://config:8888"
    ports:
      - "8761:8761"
  zuul:
    image: "dhananjay12/zuul-server:latest"
    environment:
      - "SPRING_EUREKA=http://eureka:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=${http://config:8888}"
    ports:
      - "8050:8050"
  user:
    image: "dhananjay12/user-service:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=${http://config:8888}"
    ports:
      - "8100:8100"
  contactus:
    image: "dhananjay12/contact-us-service:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=${http://config:8888}"
    ports:
      - "8080:8080"

